-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME 
from (
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME, (ANIMAL_OUTS.DATETIME - ANIMAL_INS.DATETIME) time
from ANIMAL_INS inner join ANIMAL_OUTS on ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
order by time desc
    ) where rownum < 3