-- 코드를 입력하세요
SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
from USED_GOODS_BOARD A inner join USED_GOODS_REPLY B on A.BOARD_ID = B.BOARD_ID
where A.CREATED_DATE <= '2022-10-31'
and A.CREATED_DATE >= '2022-10-01'
ORDER BY B.CREATED_DATE, A.TITLE